# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "diegoronan.com.br"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Relatos e dicas a respeito de corridas de rua, e um pouco de fotografia."

# Tagline near the site title
tagline: "Relatos, histórias, viagens e fotos."

# Tempo de leitura
reading_time:     true
words_per_minute: 200


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-844293-4


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://www.diegoronan.com.br"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: Sobre
  url: /about/
# - text: Guia de Estilos
#  url: /style-guide/
- text: Links Úteis
  url: /links/
- text: Histórico
  url: /historico/
- text: Todos os Posts
  url: /posts/
- text: Tags
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: diegoronan

# Author information - author info at the bottom of the post
author_name: "Diego Ronan"
author_bio: "Um paulistano, desenvolvedor de softwares, apaixonado por corridas, fotografia, viagens e muito rock."
author_url:  "http://www.diegoronan.com.br"
author_location: "Guarulhos, São Paulo"
author_image: /images/diego_avatar.jpg

# Sidebar Add banner
banner_url:
banner_image:


resultado:
urlmedalha:
urlmedalhafull:
captionmedalha:
numerodepeito:

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//diegoronan.us16.list-manage.com/subscribe/post?u=8e9d94ec431c96e72f0049cb6&amp;id=cafe2d08cb"

# Social links in the site footer
twitter_username: "drkulian"
facebook_username: "diego.ronan"
googleplus_username: "+DiegoRonan"
github_username: "dronan"
# codepen_username: "username"
# dribbble_uername: "username"
# medium_username: "@username"
instagram_username: "dronan"
pinterest_username: "diegoronan"
linkedin_username: "drkulian"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# http://jekyllrb.com/docs/pagination/
# Amount of post to show on home page
paginate: 5

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class



paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]


